### ISSUE TITLE
Certbot is not working 

### ISSUE THREAD

**Issue by dondonjang** [coollabsio/coolify#160]
https://github.com/coollabsio/coolify/issues/144

It seems to be related to the previous problem.
Currently certbot is not working

How can I make this function work?

**Comment by dondonjang** [comment]
it is all deployment 
I tried remove domain and add domain have same issue

certbot state is no check in HA Proxy

I just update coolify 
[v2.0.13] > [v2.0.16]
not reinstall

**Comment by andrasbacsai** [comment]
No check is normal, as the `certbot` backend is on-demand only, not running continuously. 

Could you please open the `Destination` menu and restart Coolify proxy? It will reconfigure anything automatically. 

My only guess, without any error, is that something stuck in the HAProxy configuration. The restart will solve it.

**Comment by dondonjang** [comment]
I already try force restart proxy and settings remove domain 
and add domain and checked Generate SSL for www and non-www?

**Comment by dondonjang** [comment]
if I add settings domain https://domain.com
it is return time out

**Comment by dondonjang** [comment]
I retried install sh
`/bin/bash -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"`
and settings domain 
return this error

Error: Command failed: DOCKER_HOST=unix:///var/run/docker.sock docker run -rm -name certbot-ckzwgrwfo00020qmwcita021j -p 9080:9080 -v "coolify-letsencrypt:/etc/letsencrypt" certbot/certbot -logs-dir /etc/letsencrypt/logs certonly -standalone -preferred-challenges http -http-01-address 0.0.0.0 -http-01-port 9080 -d helloio.net -d www.helloio.net -expand -agree-tos -non-interactive -register-unsafely-without-email Saving debug log to /etc/letsencrypt/logs/letsencrypt.log An unexpected error occurred: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/ Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /etc/letsencrypt/logs/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by andrasbacsai** [comment]
Ah! It often happens if you have a wrong DNS set or your server is not reachable over the internet and certbot tries too many times to generate the certificate. 

At the moment, you have to wait till the rate limit refreshes. 

I'll try to fine-tune certbot requests, but not sure if I'm able to do something with it.

**Comment by dondonjang** [comment]
is it my side issue?

**Comment by dondonjang** [comment]
I resolved this issue 
it is my domain problem
so, I changed main domain

**Comment by andrasbacsai** [comment]
That is good to hear! Thanks for letting me know!

I close the issue.

**Comment by Suleman-Elahi** [comment]
I gave up running it locally, so I deployed it on DigitalOcean. I am having the same problem...HTTPS not working. Here is my domain: https://coolify.ilovef.ga/

I followed the YouTube video tutorial; I don't know what's the problem.... how exactly did you fix it @dondonjang

**Comment by dondonjang** [comment]
@Suleman-Elahi 
Hello I replied late.
so, I do not use Coolify SSL
I set up dns ssl on https://www.cloudflare.com/ and am using it.

**Comment by Suleman-Elahi** [comment]
ok thanks

**Comment by mtgomes** [comment]
I have the same issue here.. Always HTTP and cannot make HTTPS work. I tried restarting, and nothing.
Any suggestions / possible solutions?

**Comment by andrasbacsai** [comment]
The most common problem is that DNS is not set, so Let's Encrypt cannot connect to your server and cannot validate your domain. Could you please double-check it? If it does not solve your problem, don't hesitate to get in touch with me on Discord/Telegram or any of [these](https://docs.coollabs.io/contact), so we can figure out the problem!
