### ISSUE TITLE
[Bug]: Build crashes when set "Base Directory" to "Dockerfile Location" folder

### ISSUE THREAD

**Issue by vinicioslc** [coollabsio/coolify#626]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When I set the "Base Directory" the same as my subdir to execute my Dockerfile commands, build phase crashes on the following message:
```bash
[16:45:55.354] GitHub importer started.
[16:45:55.577] Cloning vinicioslc/adverse-reactions:main branch.
[16:45:57.417] Configuration changed.
```
When clean the "Base Directory" and save, the build process continues, watch the GIF below.

![coolify-base-dir](https://user-images.githubusercontent.com/10997022/191352145-ad01a5f1-ed43-403c-973b-f77b3aa7d85c.gif)

### Steps To Reproduce

Create a monorepo
Set "Dockerfile Location" to be something like "/client/Dockerfile"
Set path to "Base Directory" to be something like "/client/"
Start the build process
Will get the messages below 
```bash
[16:45:55.354] GitHub importer started.
[16:45:55.577] Cloning vinicioslc/adverse-reactions:main branch.
[16:45:57.417] Configuration changed.
```

### Version

3.10.4

**Comment by tygore587** [comment]
Had the same issue :) Is fixed in the new version :)

**Comment by andrasbacsai** [comment]
Yes, can you please double check @vinicioslc ?

**Comment by tygore587** [comment]
> Yes, can you please double check @vinicioslc ?

What I found a bit confusing at first is that the Dockerfile location doesn't give a hint in the tooltip that it is a relative path from the base directory.

**Comment by vinicioslc** [comment]
@andrasbacsai bad news... the problem persists heheh

![image](https://user-images.githubusercontent.com/10997022/192364021-08cd1f47-b6aa-4b39-b020-21c17550ce25.png)

![image](https://user-images.githubusercontent.com/10997022/192364236-1adf4751-4224-4aa8-862d-ea589515263c.png)

**Comment by andrasbacsai** [comment]
Okay, found the issue, it is just a UX problem. It will be fixed in v3.10.9, releasing soon.

**Comment by andrasbacsai** [comment]
Your right configuration should be `baseDirectory: /client` and `dockerFileLocation: /Dockerfile`. Can you please try with these?

**Comment by vinicioslc** [comment]
Oh yeah you are right, need a UX improvement, now its working

I didn't realize it was the location of the Dockerfile it was relative to the Base Directory rather than the Repo directory

**Comment by andrasbacsai** [comment]
> @andrasbacsai Oh yeah you are right, need a UX improvement, now its working
> 
> I didn't realize it was the location of the Dockerfile it was relative to the Base Directory rather than the Repo directory

Yeah, it was not clear. but will be in the next version.
![image](https://user-images.githubusercontent.com/5845193/192447795-fbf511ff-b5ec-490b-876e-b92041b40c40.png)

**Comment by vinicioslc** [comment]
NICE! i love it !
