### ISSUE TITLE
[Bug]: Build time env not accessible from build command on `v4.0.0-beta.432`

### ISSUE THREAD

**Issue by lamualfa** [coollabsio/coolify#6737]
### Error Message and Logs

This issue only happens on `v4.0.0-beta.432`. The previous update `v4.0.0-beta.429` is works perfectly.

Currently the only solution is to pass the env directly on build command:

```bash
APP_URL=https://example.com pnpm build
```

### Steps to Reproduce

Try to echo a build time env from build command. It won't work.

### Coolify Version

v4.0.0-beta.432

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by andrasbacsai** [comment]
I tried to reproduce. 
Set build command to `env && npm run build` and set a `BUILDTIME=yes` variable. 
I can see it during build-time.

<img width="956" height="180" alt="Image" src="https://github.com/user-attachments/assets/e517a040-ac5b-4308-b3dc-e7b7b2d1972c" />

**Comment by jlucaso1** [comment]
can be related with this? https://github.com/coollabsio/coolify/issues/6731

**Comment by lamualfa** [comment]
> I tried to reproduce. Set build command to `env && npm run build` and set a `BUILDTIME=yes` variable. I can see it during build-time.
> 
> <img alt="Image" width="956" height="180" src="https://private-user-images.githubusercontent.com/5845193/495638485-e517a040-ac5b-4308-b3dc-e7b7b2d1972c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkyMzc4MTksIm5iZiI6MTc1OTIzNzUxOSwicGF0aCI6Ii81ODQ1MTkzLzQ5NTYzODQ4NS1lNTE3YTA0MC1hYzViLTQzMDgtYjNkYy1lN2I3YjJkMTk3MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MzBUMTMwNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM4YjFiZDI0YzJiZjU3MmVmNzk0MmE2MzY1MjU5ZjcyYTI3MTJjOWU2ZWVjYmNmODNhOWM4YTYzZTc3NWQyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qkIakqiiKZIs0oX0vFYQdEM_cTZhFrd290SlWbU9cV8">

try to echo it. you can't.

therea are several env related issues only on this version. i think something wrong on this version:

- https://github.com/coollabsio/coolify/issues/6731
- https://github.com/coollabsio/coolify/issues/6738

**Comment by djsisson** [comment]
@lamualfa you can't echo it in a dockerfile as it is a build secret, they are only accessible inside the run command where the secrets are mounted, i.e the build command

im not sure if coolify mounts them to all RUN commands though (i think it does)

however if buildkit is available and build secrets are disabled, they are just passed as a normal --build-arg but then you would have to manually add the ARG lines your self, as i do not think in this situation they are added

**Comment by jpmadrigal07** [comment]
My environment variables using nixpack build is not working right now.

**Comment by abdulmejidshemsuawel** [comment]
> My environment variables using nixpack build is not working right now.

same for me

**Comment by JSanchezFDZ** [comment]
Same for me

**Comment by andrasbacsai** [comment]
I will release a new version tomorrow morning with potential fix.

**Comment by lamualfa** [comment]
@andrasbacsai thanks!

**Comment by andrasbacsai** [comment]
Released v433, could you please check if its still an issue?

**Comment by lamualfa** [comment]
> Released v433, could you please check if its still an issue?

@andrasbacsai the problem still occurs on `v4.0.0-beta.433)`. i've tried deploy without cache.

is it possible to downgrade the coolify version?

**Comment by andrasbacsai** [comment]
> > Released v433, could you please check if its still an issue?
> 
> [@andrasbacsai](https://github.com/andrasbacsai) the problem still occurs on `v4.0.0-beta.433)`. i've tried deploy without cache.
> 
> is it possible to downgrade the coolify version?

Yes, you can downgrade with `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.429`.

But do you have an example repo that I can reproduce the issue? What are you using the APP_URL for on the frontend?

**Comment by lamualfa** [comment]
> Yes, you can downgrade with curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.429.

Great, thanks.

> But do you have an example repo that I can reproduce the issue? What are you using the APP_URL for on the frontend?

@andrasbacsai Sorry, i don't. But it's a nuxt v2 project. The project works perfectly on the previous version of coolify. After upgrading the coolify and redeploy the project without any changes, the project no longer working properly. And yes it is `APP_URL` env.

Let me try to downgrade it. If it's work, it must be the coolify bug on newer version.

**Comment by andrasbacsai** [comment]
> > Yes, you can downgrade with curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.429.
> 
> Great, thanks.
> 
> > But do you have an example repo that I can reproduce the issue? What are you using the APP_URL for on the frontend?
> 
> [@andrasbacsai](https://github.com/andrasbacsai) Sorry, i don't. But it's a nuxt v2 project. The project works perfectly on the previous version of coolify. After upgrading the coolify and redeploy the project without any changes, the project no longer working properly. And yes it is `APP_URL` env.
> 
> Let me try to downgrade it. If it's work, it must be the coolify bug on newer version.

Just to understand what you would like to achieve. 

You have the `APP_URL` and during the build, it will be embedded into the frontend code, so  client side, right?

**Comment by lamualfa** [comment]
@andrasbacsai I've downgraded to `v4.0.0-beta.429`. And it doesn't work. I'm not sure is this one-way problem or not. It seems once you updated from `v4.0.0-beta.429` to the newest version, you can go back to older version to solves the problem.

Let me create a new project.

**Comment by lamualfa** [comment]
> > > Yes, you can downgrade with curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.429.
> > 
> > 
> > Great, thanks.
> > > But do you have an example repo that I can reproduce the issue? What are you using the APP_URL for on the frontend?
> > 
> > 
> > [@andrasbacsai](https://github.com/andrasbacsai) Sorry, i don't. But it's a nuxt v2 project. The project works perfectly on the previous version of coolify. After upgrading the coolify and redeploy the project without any changes, the project no longer working properly. And yes it is `APP_URL` env.
> > Let me try to downgrade it. If it's work, it must be the coolify bug on newer version.
> 
> Just to understand what you would like to achieve.
> 
> You have the `APP_URL` and during the build, it will be embedded into the frontend code, so client side, right?

Yes.

**Comment by andrasbacsai** [comment]
> [@andrasbacsai](https://github.com/andrasbacsai) I've downgraded to `v4.0.0-beta.429`. And it doesn't work. I'm not sure is this one-way problem or not. It seems once you updated from `v4.0.0-beta.429` to the newest version, you can go back to older version to solves the problem.
> 
> Let me create a new project.

Thanks for making a sample project. I also made one example [here](https://github.com/coollabsio/coolify-examples/tree/v4.x/nuxt/static). 

If I generate static `npm run generate` and serve it with nginx or just build it with `npm run generate` and serve it with Nitro, the `APP_URL` is there on the frontend based on the env I set in Coolify.

**Comment by djsisson** [comment]
@lamualfa 
you have to tick 'Available at Buildtime' now in the env tab, whereas before it was sort of bugged and worked even if you didn't

**Comment by flygomel** [comment]
same with v4.0.0-beta.432 and v4.0.0-beta.433
no env vars passed on build time

```
#14 214.3 build: ERROR: command finished with error: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
2025-Oct-02 12:19:21.867970
#14 214.3 build: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
2025-Oct-02 12:19:21.867970
#14 214.4
2025-Oct-02 12:19:21.867970
#14 214.4  Tasks:    0 successful, 1 total
2025-Oct-02 12:19:21.867970
#14 214.4 Cached:    0 cached, 1 total
2025-Oct-02 12:19:21.867970
#14 214.4   Time:    3m32.536s
2025-Oct-02 12:19:21.867970
#14 214.4 Failed:    //#build
2025-Oct-02 12:19:21.867970
#14 214.4
2025-Oct-02 12:19:21.867970
#14 214.4  ERROR  run failed: command  exited (1)
2025-Oct-02 12:19:21.867970
#14 ERROR: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1
2025-Oct-02 12:19:21.867970
------
2025-Oct-02 12:19:21.867970
> [10/12] RUN  npx turbo run build:
2025-Oct-02 12:19:21.867970
214.3 build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2025-Oct-02 12:19:21.867970
214.3 build: ERROR: command finished with error: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
2025-Oct-02 12:19:21.867970
214.3 build: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
2025-Oct-02 12:19:21.867970
214.4
2025-Oct-02 12:19:21.867970
214.4  Tasks:    0 successful, 1 total
2025-Oct-02 12:19:21.867970
214.4 Cached:    0 cached, 1 total
2025-Oct-02 12:19:21.867970
214.4   Time:    3m32.536s
2025-Oct-02 12:19:21.867970
214.4 Failed:    //#build
2025-Oct-02 12:19:21.867970
214.4
2025-Oct-02 12:19:21.867970
214.4  ERROR  run failed: command  exited (1)
2025-Oct-02 12:19:21.867970
------
2025-Oct-02 12:19:21.867970
2025-Oct-02 12:19:21.867970
25 warnings found (use docker --debug to expand):
2025-Oct-02 12:19:21.867970
- SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "APPLE_PRIVATE_KEY") (line 12)
2025-Oct-02 12:19:21.867970
...
2025-Oct-02 12:19:21.867970
- UndefinedVar: Usage of undefined variable '$NIXPACKS_PATH' (line 18)
2025-Oct-02 12:19:21.867970
Dockerfile:25
2025-Oct-02 12:19:21.867970
--------------------
2025-Oct-02 12:19:21.867970
23 |     # build phase
2025-Oct-02 12:19:21.867970
24 |     COPY . /app/.
2025-Oct-02 12:19:21.867970
25 | >>> RUN  npx turbo run build
2025-Oct-02 12:19:21.867970
26 |
2025-Oct-02 12:19:21.867970
27 |
2025-Oct-02 12:19:21.867970
--------------------
2025-Oct-02 12:19:21.867970
ERROR: failed to build: failed to solve: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1
```

**Comment by andrasbacsai** [comment]
> same with v4.0.0-beta.432 and v4.0.0-beta.433
> no env vars passed on build time
> 
> ```
> #14 214.3 build: ERROR: command finished with error: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
> 2025-Oct-02 12:19:21.867970
> #14 214.3 build: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
> 2025-Oct-02 12:19:21.867970
> #14 214.4
> 2025-Oct-02 12:19:21.867970
> #14 214.4  Tasks:    0 successful, 1 total
> 2025-Oct-02 12:19:21.867970
> #14 214.4 Cached:    0 cached, 1 total
> 2025-Oct-02 12:19:21.867970
> #14 214.4   Time:    3m32.536s
> 2025-Oct-02 12:19:21.867970
> #14 214.4 Failed:    //#build
> 2025-Oct-02 12:19:21.867970
> #14 214.4
> 2025-Oct-02 12:19:21.867970
> #14 214.4  ERROR  run failed: command  exited (1)
> 2025-Oct-02 12:19:21.867970
> #14 ERROR: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1
> 2025-Oct-02 12:19:21.867970
> ------
> 2025-Oct-02 12:19:21.867970
> > [10/12] RUN  npx turbo run build:
> 2025-Oct-02 12:19:21.867970
> 214.3 build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 2025-Oct-02 12:19:21.867970
> 214.3 build: ERROR: command finished with error: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
> 2025-Oct-02 12:19:21.867970
> 214.3 build: command (/app/) /root/.nix-profile/bin/yarn run build exited (1)
> 2025-Oct-02 12:19:21.867970
> 214.4
> 2025-Oct-02 12:19:21.867970
> 214.4  Tasks:    0 successful, 1 total
> 2025-Oct-02 12:19:21.867970
> 214.4 Cached:    0 cached, 1 total
> 2025-Oct-02 12:19:21.867970
> 214.4   Time:    3m32.536s
> 2025-Oct-02 12:19:21.867970
> 214.4 Failed:    //#build
> 2025-Oct-02 12:19:21.867970
> 214.4
> 2025-Oct-02 12:19:21.867970
> 214.4  ERROR  run failed: command  exited (1)
> 2025-Oct-02 12:19:21.867970
> ------
> 2025-Oct-02 12:19:21.867970
> 2025-Oct-02 12:19:21.867970
> 25 warnings found (use docker --debug to expand):
> 2025-Oct-02 12:19:21.867970
> - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "APPLE_PRIVATE_KEY") (line 12)
> 2025-Oct-02 12:19:21.867970
> ...
> 2025-Oct-02 12:19:21.867970
> - UndefinedVar: Usage of undefined variable '$NIXPACKS_PATH' (line 18)
> 2025-Oct-02 12:19:21.867970
> Dockerfile:25
> 2025-Oct-02 12:19:21.867970
> --------------------
> 2025-Oct-02 12:19:21.867970
> 23 |     # build phase
> 2025-Oct-02 12:19:21.867970
> 24 |     COPY . /app/.
> 2025-Oct-02 12:19:21.867970
> 25 | >>> RUN  npx turbo run build
> 2025-Oct-02 12:19:21.867970
> 26 |
> 2025-Oct-02 12:19:21.867970
> 27 |
> 2025-Oct-02 12:19:21.867970
> --------------------
> 2025-Oct-02 12:19:21.867970
> ERROR: failed to build: failed to solve: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1
> ```

Can you share details about your application and its configuration? I am trying to replicate the issue.

**Comment by andrasbacsai** [comment]
I released a new version with a few fixes, but not sure that it will fix this one.

**Comment by zenoUsman** [comment]
@andrasbacsai There is another issue in v432 whenever next js build it's consume 70 percent of sever resources and the server get freeze until build completed before v432 it's working smoothly, my server have 16 gb ram only in using 4 gb still it's freezing the server.

**Comment by andrasbacsai** [comment]
> [@andrasbacsai](https://github.com/andrasbacsai) There is another issue in v432 whenever next js build it's consume 70 percent of sever resources and the server get freeze until build completed before v432 it's working smoothly, my server have 16 gb ram only in using 4 gb still it's freezing the server.

That is probably not related to Coolify. The build process did not change for a long time. Something is going on your server instead. If you come to our Discord, we can check what is going on.

**Comment by NubeBuster** [comment]
The env variables are still broken for me. They print correctly in the build log but I think at runtime they don't work. Which version do I downgrade to?

~~4.0.0-beta.429~~ ~~4.0.0-beta.425~~ ~~4.0.0-beta.427 it is. (429 didn't fix,  425 has incompatible db schema)~~
**Ugh** I am restoring from backup... I hope that works.


PROD IS DOWN :( !!!!

**Comment by zenoUsman** [comment]
> > [@andrasbacsai](https://github.com/andrasbacsai) There is another issue in v432 whenever next js build it's consume 70 percent of sever resources and the server get freeze until build completed before v432 it's working smoothly, my server have 16 gb ram only in using 4 gb still it's freezing the server.
> 
> That is probably not related to Coolify. The build process did not change for a long time. Something is going on your server instead. If you come to our Discord, we can check what is going on.

Okay I will join but this never happens before we updating app smoothly build never freeze the server like that also there is no sign of malware and control mishandled.

**Comment by NubeBuster** [comment]
> The env variables are still broken for me. They print correctly in the build log but I think at runtime they don't work. Which version do I downgrade to?
> 
> ~4.0.0-beta.429~ ~4.0.0-beta.425~ ~4.0.0-beta.427 it is. (429 didn't fix, 425 has incompatible db schema)~ **Ugh** I am restoring from backup... I hope that works.
> 
> PROD IS DOWN :( !!!!

Man what a headache. I restored to v4.0.0-beta.424 on a new VPS (I coincidentally had to migrate the server anyway) and there it works fine.

Details: I upgraded coolify and everything continued working fine. When I re-deployed my nextjs server it suddenly gave 
https://authjs.dev/reference/core/errors#untrustedhost
But since I have AUTH_TRUST_HOST=true this should not happen. NB: in the re-deploy nothing changed, except the coolify version.

In the build logs it prints AUTH_TRUST_HOST=true so I assume the issue for me is that the env var does not work at runtime.

I am currently upgrading my old server back to v4.0.0-beta.434 to see if there are any config options in the env section I misunderstood;

Looks good to me.
<img width="1293" height="168" alt="Image" src="https://github.com/user-attachments/assets/bc5c869d-9cd8-4ecb-bbf5-e01d02ab4a4e" />


```
2025-10-03T14:26:03.556482029Z web:start: [auth][error] UntrustedHost: Host must be trusted. URL was: https://hosttest.mydomain.me/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
```

Deploying the EXACT same configuration and settings does not work on v4.0.0-beta.434 but does work on v4.0.0-beta.424

This all begs me the question; are you not supposed to just update coolify in prod? I pressed the update button expecting it all to either break immediately or work. This was a painful process. Servers down for 4 hours. I'd almost say there should be a stable branch. But the versioning already let's me know, it's in BETA 🎃

**Comment by NubeBuster** [comment]
additional note:

<img width="1288" height="170" alt="Image" src="https://github.com/user-attachments/assets/19bcfd9d-c1ba-48ef-92e0-033ad2de50e0" />


2025-Oct-03 14:29:25.306930 Final Nixpacks plan: {
2025-Oct-03 14:29:25.306930 "providers": [],
2025-Oct-03 14:29:25.306930 "buildImage": "ghcr.io\/railwayapp\/nixpacks:ubuntu-1745885067",
2025-Oct-03 14:29:25.306930 "variables": {
2025-Oct-03 14:29:25.306930 "CI": "true", 



How come CI is true when I uncheck the boxes?

**Comment by andrasbacsai** [comment]
> additional note:
> 
> <img alt="Image" width="1288" height="170" src="https://private-user-images.githubusercontent.com/7793993/497188409-19bcfd9d-c1ba-48ef-92e0-033ad2de50e0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk1MDMyMzUsIm5iZiI6MTc1OTUwMjkzNSwicGF0aCI6Ii83NzkzOTkzLzQ5NzE4ODQwOS0xOWJjZmQ5ZC1jMWJhLTQ4ZWYtOTJlMC0wMzNhZDJkZTUwZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMDNUMTQ0ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmEwYzljYTEyMzdkMzJhMmFkOTI0YjFhMzNhYTBhNDEwN2FjZTVhNjFhMTM0MDMzYTM3OTNkN2MzZjcxNThhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RwUChJUHUEYyuay4txl6HPkXzAGnSsJ32plGoR3pcYE">
> 2025-Oct-03 14:29:25.306930 Final Nixpacks plan: { 2025-Oct-03 14:29:25.306930 "providers": [], 2025-Oct-03 14:29:25.306930 "buildImage": "ghcr.io/railwayapp/nixpacks:ubuntu-1745885067", 2025-Oct-03 14:29:25.306930 "variables": { 2025-Oct-03 14:29:25.306930 "CI": "true",
> 
> How come CI is true when I uncheck the boxes?

Sorry that this happened. :(

That one is added by [Nixpacks](https://nixpacks.com/docs/providers/node).
I am trying to reproduce your issue, I am working on this for the past 2 days.

**Comment by NubeBuster** [comment]
@andrasbacsai I am open in assisting you if I can. If you aren't able to reproduce then maybe it can help prodding at my setup to see what's up.

**Comment by andrasbacsai** [comment]
> [@andrasbacsai](https://github.com/andrasbacsai) I am open in assisting you if I can. If you aren't able to reproduce then maybe it can help prodding at my setup to see what's up.

That would be very helpful. Are you on Discord? If yes, can you dm me there?

**Comment by f0wu5u** [comment]
Hi @andrasbacsai, was coolify/nixpacks writing `.env` to the application root directory before?.... Because previously I used to copy the `.env` from the app root to different places during build time but now the .env file does not exist anymore... Maybe something has changed recently

**Comment by NubeBuster** [comment]
> > [@andrasbacsai](https://github.com/andrasbacsai) I am open in assisting you if I can. If you aren't able to reproduce then maybe it can help prodding at my setup to see what's up.
> 
> That would be very helpful. Are you on Discord? If yes, can you dm me there?

The invite link on your profile is expired and I can't add you by 'heyandras' . How do I add you? My username is NubeBuster

**Comment by f0wu5u** [comment]
Hi @andrasbacsai  after downgrading to [v4.0.0-beta.428](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.428), I now have the `.env` in file in the app/project root directory and my envs are now available in `nixpacks` build process... I guess the issue started at `v4.0.0-beta.429` as I couldn't get the `envs` in that build too

**Comment by lamualfa** [comment]
> Hi [@andrasbacsai](https://github.com/andrasbacsai) after downgrading to [v4.0.0-beta.428](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.428), I now have the `.env` in file in the app/project root directory and my envs are now available in `nixpacks` build process... I guess the issue started at `v4.0.0-beta.429` as I couldn't get the `envs` in that build too

confirmed. the same project working perfectly without any changes after downgrading the coolify to `v4.0.0-beta.428`. run this command to downgrade your coolify version:

```bash
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.428
```

**Comment by djsisson** [comment]
@andrasbacsai is env interpolated from other env the issue? 
I can see when not using buildkit and you inject ARG then the coolify ones are injected after their own ARG meaning they would be undefined if they are using COOLIFY env
Regarding secrets, i don't know how you are populating the environment when running the build command with --secret but again the order does matter for interpolation

**Comment by djsisson** [comment]
@andrasbacsai im not sure if this is one of the issues

https://github.com/coollabsio/coolify/blob/b4f2d8caf18f4900473e79cc203da23ca83f4ca6/app/Jobs/ApplicationDeploymentJob.php#L1953-L2018

you prepend any coolify interpolated env to the front, but then bulk put at the end of the function which would remove the prepended and just put all at the end due to unique key

could you change it to put all coolify env first, followed by the users env, no need to then check for coolify values, since they would already be defined

**Comment by andrasbacsai** [comment]
> [@andrasbacsai](https://github.com/andrasbacsai) im not sure if this is one of the issues
> 
> [coolify/app/Jobs/ApplicationDeploymentJob.php](https://github.com/coollabsio/coolify/blob/b4f2d8caf18f4900473e79cc203da23ca83f4ca6/app/Jobs/ApplicationDeploymentJob.php#L1953-L2018)
> 
> Lines 1953 to 2018 in [b4f2d8c](/coollabsio/coolify/commit/b4f2d8caf18f4900473e79cc203da23ca83f4ca6)
> 
>  private function generate_env_variables() 
>  { 
>      $this->env_args = collect([]); 
>      $this->env_args->put('SOURCE_COMMIT', $this->commit); 
>      $coolify_envs = $this->generate_coolify_env_variables(); 
>      // For build process, include only environment variables where is_buildtime = true 
>      if ($this->pull_request_id === 0) { 
>          // Get environment variables that are marked as available during build 
>          $envs = $this->application->environment_variables() 
>              ->where('key', 'not like', 'NIXPACKS_%') 
>              ->where('is_buildtime', true) 
>              ->get(); 
>   
>          foreach ($envs as $env) { 
>              if (! is_null($env->real_value)) { 
>                  $this->env_args->put($env->key, $env->real_value); 
>                  if (str($env->real_value)->startsWith('$')) { 
>                      $variable_key = str($env->real_value)->after('$'); 
>                      if ($variable_key->startsWith('COOLIFY_')) { 
>                          $variable = $coolify_envs->get($variable_key->value()); 
>                          if (filled($variable)) { 
>                              $this->env_args->prepend($variable, $variable_key->value()); 
>                          } 
>                      } else { 
>                          $variable = $this->application->environment_variables()->where('key', $variable_key)->first(); 
>                          if ($variable) { 
>                              $this->env_args->prepend($variable->real_value, $env->key); 
>                          } 
>                      } 
>                  } 
>              } 
>          } 
>      } else { 
>          // Get preview environment variables that are marked as available during build 
>          $envs = $this->application->environment_variables_preview() 
>              ->where('key', 'not like', 'NIXPACKS_%') 
>              ->where('is_buildtime', true) 
>              ->get(); 
>   
>          foreach ($envs as $env) { 
>              if (! is_null($env->real_value)) { 
>                  $this->env_args->put($env->key, $env->real_value); 
>                  if (str($env->real_value)->startsWith('$')) { 
>                      $variable_key = str($env->real_value)->after('$'); 
>                      if ($variable_key->startsWith('COOLIFY_')) { 
>                          $variable = $coolify_envs->get($variable_key->value()); 
>                          if (filled($variable)) { 
>                              $this->env_args->prepend($variable, $variable_key->value()); 
>                          } 
>                      } else { 
>                          $variable = $this->application->environment_variables_preview()->where('key', $variable_key)->first(); 
>                          if ($variable) { 
>                              $this->env_args->prepend($variable->real_value, $env->key); 
>                          } 
>                      } 
>                  } 
>              } 
>          } 
>      } 
>   
>      // Merge COOLIFY_* variables into env_args for build process 
>      // This ensures they're available for both build args and build secrets 
>      $coolify_envs->each(function ($value, $key) { 
>          $this->env_args->put($key, $value); 
>      }); 
>  } 
> you prepend any coolify interpolated env to the front, but then bulk put at the end of the function which would remove the prepended and just put all at the end due to unique key
> 
> could you change it to put all coolify env first, followed by the users env, no need to then check for coolify values, since they would already be defined

Thanks, I fixed that with [this](https://github.com/coollabsio/coolify/pull/6758/commits/158747c8b133c852dc1bf0e626ee4e5246292efa).

**Comment by djsisson** [comment]
i think i see another issue when build secrets is off

https://github.com/coollabsio/coolify/blob/b4f2d8caf18f4900473e79cc203da23ca83f4ca6/app/Jobs/ApplicationDeploymentJob.php#L2822

docker build does not do any interpolation, so any build args that reference another env would just be taken as a string and not interpolated, i.e APP_URL=$COOLIFY_URL would never get interpolated, docker compose will interpolate from a .env, but docker buildx build will not

so you either need to do the interpolation manually (not recommended) or export the .env file before running docker build, that way you only need to pass in --build-arg keys , any values would be sourced from the environment

you can do this by running ```export $(grep -v '^#' .env | xargs)``` before the build command

the oop roughly for me would be

1) create .env in build container outside repo directory (needed when running compose build)
2) add all coolify env
3) add all user build env
4) collection of --secret keys or --build-arg keys (no values) consisting of all coolify + user build time keys
5) run  ```export $(grep -v '^#' .env | xargs)``` followed by ```docker buildx build ...keys ``` for normal builds
6) run ```docker compose build --env_file``` for compose builds and let compose interpolate

**Comment by andrasbacsai** [comment]
> i think i see another issue when build secrets is off
> 
> [coolify/app/Jobs/ApplicationDeploymentJob.php](https://github.com/coollabsio/coolify/blob/b4f2d8caf18f4900473e79cc203da23ca83f4ca6/app/Jobs/ApplicationDeploymentJob.php#L2822)
> 
> Line 2822 in [b4f2d8c](/coollabsio/coolify/commit/b4f2d8caf18f4900473e79cc203da23ca83f4ca6)
> 
>  $this->build_args = generateDockerBuildArgs($vars_with_metadata); 
> docker build does not do any interpolation, so any build args that reference another env would just be taken as a string and not interpolated, i.e APP_URL=$COOLIFY_URL would never get interpolated, docker compose will interpolate from a .env, but docker buildx build will not
> 
> so you either need to do the interpolation manually (not recommended) or export the .env file before running docker build, that way you only need to pass in --build-arg keys , any values would be sourced from the environment
> 
> you can do this by running `export $(grep -v '^#' .env | xargs)` before the build command
> 
> the oop roughly for me would be
> 
> 1. create .env in build container outside repo directory (needed when running compose build)
> 2. add all coolify env
> 3. add all user build env
> 4. collection of --secret keys or --build-arg keys (no values) consisting of all coolify + user build time keys
> 5. run  `export $(grep -v '^#' .env | xargs)` followed by `docker buildx build ...keys ` for normal builds
> 6. run `docker compose build --env_file` for compose builds and let compose interpolate

Oh wow. Thanks @djsisson!! 💜

You are right. I was so distracted by other things that I did not found this.

After changing the behaviour the build command looks like this and it works!

I also changed the whole .env generation process, separated the build and runtime stuffs properly, so it looks better at code and in execution.

I also moved the build-time.env out of the context, which is good and bad at the same time. Security point of view good, but we need to document it as some people copy it in other places manually during the build (but maybe they don't need it after the changes).

**Comment by andrasbacsai** [comment]
@lamualfa can you please try to manually upgrade to the next version and test out if it works now?

`docker pull coollabsio/coolify:next && curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s next`

This will upgrade your Coolify instance to the next, unreleased version.

**Comment by lamualfa** [comment]
> `docker pull coollabsio/coolify:next && curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s next`

ok. lemme try it

**Comment by lamualfa** [comment]
@andrasbacsai it doesn't work. and it's working again after downgrading it.

**Comment by andrasbacsai** [comment]
> [@andrasbacsai](https://github.com/andrasbacsai) it doesn't work. and it's working again after downgrading it.

That is so strange. Every other env related bugs disappeared in the next version (tested by others).

Are you on Discord? Can you please ping me there?

**Comment by asieduernest12** [comment]
> [@lamualfa](https://github.com/lamualfa) can you please try to manually upgrade to the next version and test out if it works now?
> 
> `docker pull coollabsio/coolify:next && curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s next`
> 
> This will upgrade your Coolify instance to the next, unreleased version.

solved my issue related issues. something about envs failing.
@andrasbacsai thank you

**Comment by jpmadrigal07** [comment]
This has been my issue since beta 432, I have turborepo with nextjs and node express deployment with Nixpack. I use dotenv settings for both my local and on my self-hosted coolify, i'm getting the `.env` from the root folder and it works even if I don't generate it. Since 432 until 436, it didn't work. I don't want to downgrade like @lamualfa did. What I did is to change Nixpack to Docker compose settings and manually create .env in Entrypoint bash file.
