### ISSUE TITLE
[Bug]: SERVICE_NAME_ variables are unavailable

### ISSUE THREAD

**Issue by krzkz94** [coollabsio/coolify#6746]
### Error Message and Logs

Unknown variable; There is no variable named "SERVICE_NAME_MYSQL"

### Steps to Reproduce

1. Create a coolify project with docker compose, two services, api and mysql
2. Reference SERVICE_NAME_MYSQL inside DATABASE_HOST=${SERVICE_NAME_MYSQL} for preview deployments
3. Try deploying the preview deployment
4. Deployment fails as variable doesn't exist

### Coolify Version

v4.0.0-beta.432

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 25

### Additional Information

This was working fine after it was released but broke at some point
SERVICE_FQDN, SERVICE_URL are set correctly

**Comment by nurdism** [comment]
Finding similar issues with predefined environment variables, will attempt to debug a bit more and submit a reproduction repo soon

**Comment by jpmadrigal07** [comment]
v4.0.0-beta.432 is faulty in terms of env vars. these are the reported issues connecting to it.

#6731 
#6737 

What I experience is all of my declared env with my turborepo express.js app are all undefined since v4.0.0-beta.432 version. They release a fix for that issue in v4.0.0-beta.433 but still the bug persist on my self-hosted instance.

**Comment by andrasbacsai** [comment]
I tried to reproduce the issue, but I could not.

I released a new version with a few fixes, but not sure that it will fix this one. Can you please check with it?

**Comment by krzkz94** [comment]
Seems like they are present in the docker-compose but can't be interpolated from the environment variables

So if under environment variables I have DATABASE_HOST=${SERVICE_NAME_MYSQL} it won't work (it used to)

These variables are defined at the docker-compose level but not at the "Environment Variables" level

docker-compose
<img width="484" height="136" alt="Image" src="https://github.com/user-attachments/assets/b4cee47d-0b85-407d-b92d-8dfe6246e2f2" />

env-variables (preview)

<img width="232" height="321" alt="Image" src="https://github.com/user-attachments/assets/0e8b1827-9071-498e-88f8-781b71a268ac" />

env-variables (prod)
<img width="234" height="322" alt="Image" src="https://github.com/user-attachments/assets/797b819a-bf16-4ddb-8555-93cc53427f83" />

**Comment by andrasbacsai** [comment]
@krzkz94 can you please try to manually upgrade to the next version and test out if it works now?

`docker pull coollabsio/coolify:next && curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s next`

This will upgrade your Coolify instance to the next, unreleased version.

**Comment by krzkz94** [comment]
@andrasbacsai 

I can confirm that after upgrading to the latest (next) edition, the env variables in question are still not showing up

```
2025-Oct-07 14:45:56.856922
Oops something is not okay, are you okay? 😢
2025-Oct-07 14:45:56.871224
-.json:42,27-45: Unknown variable; There is no variable named "SERVICE_NAME_MYSQL"., and 10 other diagnostic(s)
```

Attaching screenshots

Variables in Docker Compose (good)

<img width="348" height="427" alt="Image" src="https://github.com/user-attachments/assets/e3580b51-f093-49e1-aaf2-c7b3af8b30a2" />

Variables in Environment Variables (missing SERVICE_NAME_, bad)

<img width="229" height="670" alt="Image" src="https://github.com/user-attachments/assets/d39613e9-e206-49ba-bb1e-2f823c5469a9" />

As you can see, the SERVICE_NAME_ variables are nowhere to be found here nor are injected during the build process

**Comment by sovetski** [comment]
Same problem [here](https://github.com/coollabsio/coolify/issues/7014)
